# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consulta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consulta.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x63onsulta.proto\">\n\x08\x43onsulta\x12\x0b\n\x03\x61no\x18\x01 \x01(\r\x12\x19\n\x11\x63odigo_disciplina\x18\x02 \x01(\x04\x12\n\n\x02op\x18\x03 \x01(\rb\x06proto3')
)




_CONSULTA = _descriptor.Descriptor(
  name='Consulta',
  full_name='Consulta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ano', full_name='Consulta.ano', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codigo_disciplina', full_name='Consulta.codigo_disciplina', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='Consulta.op', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['Consulta'] = _CONSULTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Consulta = _reflection.GeneratedProtocolMessageType('Consulta', (_message.Message,), dict(
  DESCRIPTOR = _CONSULTA,
  __module__ = 'consulta_pb2'
  # @@protoc_insertion_point(class_scope:Consulta)
  ))
_sym_db.RegisterMessage(Consulta)


# @@protoc_insertion_point(module_scope)
